source 'http://rubygems.org'

gem 'rails', '~> 6.1.4'
gem 'avatares', :path => '../../'
gem 'factory_bot_rails'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "sqlite3", :platform => [:ruby, :mswin, :mingw]
gem "jdbc-sqlite3", :platform => :jruby

gem "active_storage_validations"
